//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BitShareData
{
    public partial class ArquivoTorrent
    {
        #region Primitive Properties
    
        public virtual int IdArquivoTorrent
        {
            get;
            set;
        }
    
        public virtual string Nome
        {
            get;
            set;
        }
    
        public virtual double Tamanho
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Torrent Torrent
        {
            get { return _torrent; }
            set
            {
                if (!ReferenceEquals(_torrent, value))
                {
                    var previousValue = _torrent;
                    _torrent = value;
                    FixupTorrent(previousValue);
                }
            }
        }
        private Torrent _torrent;

        #endregion

        #region Association Fixup
    
        private void FixupTorrent(Torrent previousValue)
        {
            if (previousValue != null && previousValue.ArquivoTorrents.Contains(this))
            {
                previousValue.ArquivoTorrents.Remove(this);
            }
    
            if (Torrent != null)
            {
                if (!Torrent.ArquivoTorrents.Contains(this))
                {
                    Torrent.ArquivoTorrents.Add(this);
                }
            }
        }

        #endregion

    }
}
