//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BitShareData
{
    public partial class Ator
    {
        #region Primitive Properties
    
        public virtual int IdAtor
        {
            get;
            set;
        }
    
        public virtual string Nome
        {
            get;
            set;
        }
    
        public virtual string IdImdb
        {
            get;
            set;
        }
    
        public virtual string URLFoto
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Papel> Papels
        {
            get
            {
                if (_papels == null)
                {
                    var newCollection = new FixupCollection<Papel>();
                    newCollection.CollectionChanged += FixupPapels;
                    _papels = newCollection;
                }
                return _papels;
            }
            set
            {
                if (!ReferenceEquals(_papels, value))
                {
                    var previousValue = _papels as FixupCollection<Papel>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPapels;
                    }
                    _papels = value;
                    var newValue = value as FixupCollection<Papel>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPapels;
                    }
                }
            }
        }
        private ICollection<Papel> _papels;

        #endregion

        #region Association Fixup
    
        private void FixupPapels(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Papel item in e.NewItems)
                {
                    item.Ator = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Papel item in e.OldItems)
                {
                    if (ReferenceEquals(item.Ator, this))
                    {
                        item.Ator = null;
                    }
                }
            }
        }

        #endregion

    }
}
