//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BitShareData
{
    public partial class Client
    {
        #region Primitive Properties
    
        public virtual int IdClient
        {
            get;
            set;
        }
    
        public virtual string PeerID
        {
            get;
            set;
        }
    
        public virtual string Nome
        {
            get;
            set;
        }

        #endregion

    }
}
