//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BitShareData
{
    public partial class DetalheTorrent
    {
        #region Primitive Properties
    
        public virtual int IdDetalheTorrent
        {
            get;
            set;
        }
    
        public virtual string Descricao
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Torrent Torrent
        {
            get { return _torrent; }
            set
            {
                if (!ReferenceEquals(_torrent, value))
                {
                    var previousValue = _torrent;
                    _torrent = value;
                    FixupTorrent(previousValue);
                }
            }
        }
        private Torrent _torrent;

        #endregion

        #region Association Fixup
    
        private void FixupTorrent(Torrent previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.DetalheTorrent, this))
            {
                previousValue.DetalheTorrent = null;
            }
    
            if (Torrent != null)
            {
                Torrent.DetalheTorrent = this;
            }
        }

        #endregion

    }
}
