//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BitShareData
{
    public partial class EventoAnnounce
    {
        #region Primitive Properties
    
        public virtual int IdEventoAnnounce
        {
            get;
            set;
        }
    
        public virtual string HashInfoTorrent
        {
            get;
            set;
        }
    
        public virtual string PasskeyUsuario
        {
            get;
            set;
        }
    
        public virtual double Uploaded
        {
            get;
            set;
        }
    
        public virtual double Downloaded
        {
            get;
            set;
        }
    
        public virtual string Evento
        {
            get;
            set;
        }
    
        public virtual System.DateTime DataEvento
        {
            get;
            set;
        }
    
        public virtual bool Processado
        {
            get;
            set;
        }
    
        public virtual string EnderecoIP
        {
            get;
            set;
        }
    
        public virtual string PeerID
        {
            get;
            set;
        }

        #endregion

    }
}
