//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BitShareData
{
    public partial class Filme
    {
        #region Primitive Properties
    
        public virtual int IdFilme
        {
            get;
            set;
        }
    
        public virtual string Nome
        {
            get;
            set;
        }
    
        public virtual string Diretor
        {
            get;
            set;
        }
    
        public virtual string Sinopse
        {
            get;
            set;
        }
    
        public virtual string AnoLancamento
        {
            get;
            set;
        }
    
        public virtual string IdImdb
        {
            get;
            set;
        }
    
        public virtual string URLPoster
        {
            get;
            set;
        }
    
        public virtual string Generos
        {
            get;
            set;
        }
    
        public virtual string TrailerYoutube
        {
            get;
            set;
        }
    
        public virtual string ScreenShots
        {
            get;
            set;
        }
    
        public virtual string Duracao
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Papel> Papels
        {
            get
            {
                if (_papels == null)
                {
                    var newCollection = new FixupCollection<Papel>();
                    newCollection.CollectionChanged += FixupPapels;
                    _papels = newCollection;
                }
                return _papels;
            }
            set
            {
                if (!ReferenceEquals(_papels, value))
                {
                    var previousValue = _papels as FixupCollection<Papel>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPapels;
                    }
                    _papels = value;
                    var newValue = value as FixupCollection<Papel>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPapels;
                    }
                }
            }
        }
        private ICollection<Papel> _papels;
    
        public virtual ICollection<Torrent> Torrents
        {
            get
            {
                if (_torrents == null)
                {
                    var newCollection = new FixupCollection<Torrent>();
                    newCollection.CollectionChanged += FixupTorrents;
                    _torrents = newCollection;
                }
                return _torrents;
            }
            set
            {
                if (!ReferenceEquals(_torrents, value))
                {
                    var previousValue = _torrents as FixupCollection<Torrent>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTorrents;
                    }
                    _torrents = value;
                    var newValue = value as FixupCollection<Torrent>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTorrents;
                    }
                }
            }
        }
        private ICollection<Torrent> _torrents;
    
        public virtual ICollection<Legenda> Legendas
        {
            get
            {
                if (_legendas == null)
                {
                    var newCollection = new FixupCollection<Legenda>();
                    newCollection.CollectionChanged += FixupLegendas;
                    _legendas = newCollection;
                }
                return _legendas;
            }
            set
            {
                if (!ReferenceEquals(_legendas, value))
                {
                    var previousValue = _legendas as FixupCollection<Legenda>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLegendas;
                    }
                    _legendas = value;
                    var newValue = value as FixupCollection<Legenda>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLegendas;
                    }
                }
            }
        }
        private ICollection<Legenda> _legendas;
    
        public virtual PackFilme PackFilme
        {
            get { return _packFilme; }
            set
            {
                if (!ReferenceEquals(_packFilme, value))
                {
                    var previousValue = _packFilme;
                    _packFilme = value;
                    FixupPackFilme(previousValue);
                }
            }
        }
        private PackFilme _packFilme;

        #endregion

        #region Association Fixup
    
        private void FixupPackFilme(PackFilme previousValue)
        {
            if (previousValue != null && previousValue.Filmes.Contains(this))
            {
                previousValue.Filmes.Remove(this);
            }
    
            if (PackFilme != null)
            {
                if (!PackFilme.Filmes.Contains(this))
                {
                    PackFilme.Filmes.Add(this);
                }
            }
        }
    
        private void FixupPapels(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Papel item in e.NewItems)
                {
                    item.Filme = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Papel item in e.OldItems)
                {
                    if (ReferenceEquals(item.Filme, this))
                    {
                        item.Filme = null;
                    }
                }
            }
        }
    
        private void FixupTorrents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Torrent item in e.NewItems)
                {
                    item.Filme = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Torrent item in e.OldItems)
                {
                    if (ReferenceEquals(item.Filme, this))
                    {
                        item.Filme = null;
                    }
                }
            }
        }
    
        private void FixupLegendas(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Legenda item in e.NewItems)
                {
                    item.Filme = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Legenda item in e.OldItems)
                {
                    if (ReferenceEquals(item.Filme, this))
                    {
                        item.Filme = null;
                    }
                }
            }
        }

        #endregion

    }
}
