//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BitShareData
{
    public partial class Legenda
    {
        #region Primitive Properties
    
        public virtual int IdLegenda
        {
            get;
            set;
        }
    
        public virtual string Arquivo
        {
            get;
            set;
        }
    
        public virtual string Idioma
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual DetalheTorrent DetalheTorrent
        {
            get { return _detalheTorrent; }
            set
            {
                if (!ReferenceEquals(_detalheTorrent, value))
                {
                    var previousValue = _detalheTorrent;
                    _detalheTorrent = value;
                    FixupDetalheTorrent(previousValue);
                }
            }
        }
        private DetalheTorrent _detalheTorrent;

        #endregion

        #region Association Fixup
    
        private void FixupDetalheTorrent(DetalheTorrent previousValue)
        {
            if (previousValue != null && previousValue.Legendas.Contains(this))
            {
                previousValue.Legendas.Remove(this);
            }
    
            if (DetalheTorrent != null)
            {
                if (!DetalheTorrent.Legendas.Contains(this))
                {
                    DetalheTorrent.Legendas.Add(this);
                }
            }
        }

        #endregion

    }
}
