//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BitShareData
{
    public partial class Mensagem
    {
        #region Primitive Properties
    
        public virtual int IdMensagem
        {
            get;
            set;
        }
    
        public virtual string AssuntoMensagem
        {
            get;
            set;
        }
    
        public virtual string TextoMensagem
        {
            get;
            set;
        }
    
        public virtual bool Lida
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Usuario UsuarioDe
        {
            get { return _usuarioDe; }
            set
            {
                if (!ReferenceEquals(_usuarioDe, value))
                {
                    var previousValue = _usuarioDe;
                    _usuarioDe = value;
                    FixupUsuarioDe(previousValue);
                }
            }
        }
        private Usuario _usuarioDe;
    
        public virtual Usuario UsuarioPara
        {
            get { return _usuarioPara; }
            set
            {
                if (!ReferenceEquals(_usuarioPara, value))
                {
                    var previousValue = _usuarioPara;
                    _usuarioPara = value;
                    FixupUsuarioPara(previousValue);
                }
            }
        }
        private Usuario _usuarioPara;

        #endregion

        #region Association Fixup
    
        private void FixupUsuarioDe(Usuario previousValue)
        {
            if (previousValue != null && previousValue.MensagensSaida.Contains(this))
            {
                previousValue.MensagensSaida.Remove(this);
            }
    
            if (UsuarioDe != null)
            {
                if (!UsuarioDe.MensagensSaida.Contains(this))
                {
                    UsuarioDe.MensagensSaida.Add(this);
                }
            }
        }
    
        private void FixupUsuarioPara(Usuario previousValue)
        {
            if (previousValue != null && previousValue.MensagensEntrada.Contains(this))
            {
                previousValue.MensagensEntrada.Remove(this);
            }
    
            if (UsuarioPara != null)
            {
                if (!UsuarioPara.MensagensEntrada.Contains(this))
                {
                    UsuarioPara.MensagensEntrada.Add(this);
                }
            }
        }

        #endregion

    }
}
