//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace BitShareData
{
    public partial class BitShareContainer : ObjectContext
    {
        public const string ConnectionString = "name=BitShareContainer";
        public const string ContainerName = "BitShareContainer";
    
        #region Constructors
    
        public BitShareContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public BitShareContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public BitShareContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Usuario> Usuarios
        {
            get { return _usuarios  ?? (_usuarios = CreateObjectSet<Usuario>("Usuarios")); }
        }
        private ObjectSet<Usuario> _usuarios;
    
        public ObjectSet<Torrent> Torrents
        {
            get { return _torrents  ?? (_torrents = CreateObjectSet<Torrent>("Torrents")); }
        }
        private ObjectSet<Torrent> _torrents;
    
        public ObjectSet<ArquivoTorrent> ArquivosTorrents
        {
            get { return _arquivosTorrents  ?? (_arquivosTorrents = CreateObjectSet<ArquivoTorrent>("ArquivosTorrents")); }
        }
        private ObjectSet<ArquivoTorrent> _arquivosTorrents;
    
        public ObjectSet<TorrentSeed> TorrentSeeds
        {
            get { return _torrentSeeds  ?? (_torrentSeeds = CreateObjectSet<TorrentSeed>("TorrentSeeds")); }
        }
        private ObjectSet<TorrentSeed> _torrentSeeds;
    
        public ObjectSet<TorrentLeech> TorrentLeeches
        {
            get { return _torrentLeeches  ?? (_torrentLeeches = CreateObjectSet<TorrentLeech>("TorrentLeeches")); }
        }
        private ObjectSet<TorrentLeech> _torrentLeeches;
    
        public ObjectSet<TokenRegistro> TokensRegistro
        {
            get { return _tokensRegistro  ?? (_tokensRegistro = CreateObjectSet<TokenRegistro>("TokensRegistro")); }
        }
        private ObjectSet<TokenRegistro> _tokensRegistro;
    
        public ObjectSet<DetalheTorrent> DetalheTorrents
        {
            get { return _detalheTorrents  ?? (_detalheTorrents = CreateObjectSet<DetalheTorrent>("DetalheTorrents")); }
        }
        private ObjectSet<DetalheTorrent> _detalheTorrents;
    
        public ObjectSet<EventoAnnounce> EventosAnnounce
        {
            get { return _eventosAnnounce  ?? (_eventosAnnounce = CreateObjectSet<EventoAnnounce>("EventosAnnounce")); }
        }
        private ObjectSet<EventoAnnounce> _eventosAnnounce;
    
        public ObjectSet<Client> Clients
        {
            get { return _clients  ?? (_clients = CreateObjectSet<Client>("Clients")); }
        }
        private ObjectSet<Client> _clients;

        #endregion

    }
}
