//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace BitShareData
{
    public partial class PackFilme
    {
        #region Primitive Properties
    
        public virtual int IdPack
        {
            get;
            set;
        }
    
        public virtual string NomePack
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Filme> Filmes
        {
            get
            {
                if (_filmes == null)
                {
                    var newCollection = new FixupCollection<Filme>();
                    newCollection.CollectionChanged += FixupFilmes;
                    _filmes = newCollection;
                }
                return _filmes;
            }
            set
            {
                if (!ReferenceEquals(_filmes, value))
                {
                    var previousValue = _filmes as FixupCollection<Filme>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupFilmes;
                    }
                    _filmes = value;
                    var newValue = value as FixupCollection<Filme>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupFilmes;
                    }
                }
            }
        }
        private ICollection<Filme> _filmes;

        #endregion

        #region Association Fixup
    
        private void FixupFilmes(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Filme item in e.NewItems)
                {
                    item.PackFilme = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Filme item in e.OldItems)
                {
                    if (ReferenceEquals(item.PackFilme, this))
                    {
                        item.PackFilme = null;
                    }
                }
            }
        }

        #endregion

    }
}
